version: '3.8'

services:
  mysql:
    image: mysql:8.0.30-debian
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    ports:
      - 13306:3306
    volumes:
      - ./sample_db/:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
